# frozen_string_literal: true

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30

Documentation:
  Enabled: false
