# frozen_string_literal: true

require 'pry'
require 'i18n'
require 'yaml'
require_relative 'lib/app/i18n_config'
require_relative 'lib/app/modules/validator'
require_relative 'lib/app/entities/game'
require_relative 'lib/app/entities/game'
require_relative 'lib/app/entities/data_storage'
require_relative 'lib/app/entities/processor'
require_relative 'lib/app/entities/menu'
require_relative 'lib/app/entities/renderer'
require_relative 'lib/app/entities/statistics'
require_relative 'lib/codebreaker/version'
