# frozen_string_literal: true

require 'rspec'
require 'pry'
require 'i18n'
require 'yaml'
require_relative 'lib/i18n_config'
require_relative 'lib/modules/validator'
require_relative 'lib/modules/commands'
require_relative 'lib/entities/game'
require_relative 'lib/entities/data_storage'
require_relative 'lib/entities/processor'
require_relative 'lib/entities/menu'
require_relative 'lib/entities/renderer'
require_relative 'lib/entities/statistics'
